# Generated by Django 5.2.3 on 2025-08-30 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('activity', models.CharField(choices=[('YCLP Class', 'YCLP Class'), ('DREAMS Summer Camp', 'DREAMS Summer Camp'), ('DREAMS Follow-up', 'DREAMS Follow-up'), ('Others', 'Others')], default='YCLP Class', max_length=255)),
                ('other_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('learnings', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
