# Generated by Django 5.2.3 on 2025-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('YCLP-Class', 'YCLP-Class'), ('DREAMS Summer Camp', 'DREAMS Summer Camp'), ('DREAMS Follow-Up', 'DREAMS Follow-Up'), ('Others', 'Others')], default='YCLP-Class', max_length=255),
        ),
    ]
