# Generated by Django 5.2.3 on 2025-09-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_endorser_mentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('endorser', 'Endorser'), ('mentee', 'Mentee')], max_length=20),
        ),
    ]
