# Generated by Django 5.2.3 on 2025-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_role_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentee',
            new_name='Mentor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('endorser', 'Endorser'), ('mentor', 'Mentor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_group',
            field=models.CharField(choices=[('endorser', 'Endorser'), ('mentor', 'Mentor'), ('both', 'Both')], max_length=20),
        ),
    ]
