# Generated by Django 5.2.3 on 2025-10-03 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mentorprofile_assignment_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='assigned_endorsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
