# Generated by Django 5.2.3 on 2025-11-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_endorser_assigned_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Endorser',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
