# Generated by Django 5.2.3 on 2025-11-08 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_mentor_user_delete_endorser_delete_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='mentor',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='endorser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workschedule',
            name='mentors',
            field=models.ManyToManyField(related_name='mentor_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
