# Generated by Django 5.2.3 on 2025-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_workschedule_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
