# Generated by Django 5.2.3 on 2025-12-26 10:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_activity_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('current_year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')])),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_mentor', models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mentees', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MenteeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')])),
                ('date', models.DateField()),
                ('theme_topic', models.CharField(blank=True, max_length=200)),
                ('beginning_mood', models.CharField(blank=True, max_length=100)),
                ('end_mood', models.CharField(blank=True, max_length=100)),
                ('mentor_remarks', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.mentee')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentee_assessments', to=settings.AUTH_USER_MODEL)),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sessiontype')),
            ],
            options={
                'ordering': ['-date', 'mentee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='RatingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')])),
                ('name', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('objective', 'Objective'), ('tracker', 'Tracker')], max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['year', 'sort_order', 'name'],
                'unique_together': {('year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.menteeassessment')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ratingdomain')),
            ],
            options={
                'ordering': ['domain__year', 'domain__sort_order', 'domain__name'],
                'unique_together': {('assessment', 'domain')},
            },
        ),
    ]
