# Generated by Codex on 2025-12-26

from django.db import migrations


def seed_domains(apps, schema_editor):
    RatingDomain = apps.get_model("core", "RatingDomain")

    def normalize(name):
        return " ".join(name.split()).strip().lower()

    tracker = {
        1: [
            "Session Engagement",
            "Self-Awareness and Growth",
            "Emotional and Behavioral Regulation",
            "Initiative and Responsibility",
            "Mentorship and Reflection",
        ],
        2: [
            "Receiving Feedback",
            "Help-Seeking Behavior",
            "Team Work",
            "Respect",
            "Accountability",
        ],
        3: [
            "Leadership Management",
            "Decision Making",
            "Time Management",
            "Value-Based Action",
            "Conflict Navigation",
        ],
    }

    objective_raw = {
        1: [
            "Session Engagement",
            "Self-Awareness and Growth",
            "Emotional and Behavioral Regulation",
            "Initiatiative and responsibility",
            "Self-esteem and growth",
        ],
        2: [
            "Receiving Feedback",
            "Help-Seeking Behavior",
            "Help giving behavior",
            "Respect",
            "Accountability",
        ],
        3: [
            "Collaborative conflict Navigation",
            "Decision Making and team work",
            "Time and Mood management",
            "Value-Based action",
            "Relationship mappimg",
        ],
    }

    objective_map = {
        "Initiatiative and responsibility": "Initiative and Responsibility",
        "Self-esteem and growth": "Self-Esteem and Growth",
        "Help giving behavior": "Help Giving Behavior",
        "Collaborative conflict Navigation": "Conflict Navigation",
        "Decision Making and team work": "Decision Making",
        "Time and Mood management": "Time Management",
        "Value-Based action": "Value-Based Action",
        "Relationship mappimg": "Relationship Mapping",
    }

    for year, names in tracker.items():
        for idx, name in enumerate(names, start=1):
            RatingDomain.objects.update_or_create(
                year=year,
                name=name,
                defaults={
                    "source": "tracker",
                    "sort_order": idx,
                    "is_active": True,
                },
            )

    for year, names in objective_raw.items():
        tracker_names = {normalize(n) for n in tracker.get(year, [])}
        sort_order = len(tracker.get(year, [])) + 1
        for name in names:
            mapped = objective_map.get(name, name)
            if normalize(mapped) in tracker_names:
                continue
            RatingDomain.objects.update_or_create(
                year=year,
                name=mapped,
                defaults={
                    "source": "objective",
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )
            sort_order += 1


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_school_sessiontype_mentee_menteeassessment_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_domains, migrations.RunPython.noop),
    ]
