# Generated by Django 5.2.3 on 2025-12-26 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_rating_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('mood_types', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StatusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mentee',
            name='batch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentee',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mentee',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='programme',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mentee',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'mentee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='affiliation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('endorser', 'Endorser'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('reviewer', 'Reviewer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='current_year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')]),
        ),
        migrations.AlterField(
            model_name='menteeassessment',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')]),
        ),
        migrations.AlterField(
            model_name='ratingdomain',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')]),
        ),
        migrations.CreateModel(
            name='ObjectiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_title', models.CharField(blank=True, max_length=200)),
                ('objective_text', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('mentee_remarks', models.TextField(blank=True)),
                ('mentor_comments', models.TextField(blank=True)),
                ('mentor_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_items_created', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_items', to='core.mentee')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_items_updated', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.statusconfig')),
            ],
            options={
                'ordering': ['-updated_at', 'objective_title'],
            },
        ),
        migrations.CreateModel(
            name='TemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('objective', 'Objective'), ('year_plan', 'Year Plan')], max_length=20)),
                ('year', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], null=True)),
                ('fields_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['scope', 'year', 'name'],
                'unique_together': {('scope', 'year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='YearPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('milestone', models.CharField(max_length=200)),
                ('deliverable', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('target_period', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('mentor_comments', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_plan_items_created', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_plan_items', to='core.mentee')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.statusconfig')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_plan_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorMenteeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='core.mentee')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentee_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('mentor', 'mentee', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='RatingScaleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scale_definitions', to='core.ratingdomain')),
            ],
            options={
                'ordering': ['domain__year', 'domain__sort_order', 'score'],
                'unique_together': {('domain', 'score')},
            },
        ),
    ]
