# Generated by Django 5.2.3 on 2025-12-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_moodcategory_referencecontent_statusconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='core.ratingdomain')),
            ],
            options={
                'ordering': ['domain__year', 'domain__sort_order', 'sort_order'],
                'unique_together': {('domain', 'sort_order')},
            },
        ),
    ]
