# Generated by Codex on 2025-12-26

from django.db import migrations


def seed_statuses(apps, schema_editor):
    StatusConfig = apps.get_model("core", "StatusConfig")
    defaults = [
        ("Not Started", 1),
        ("In Progress", 2),
        ("Completed", 3),
        ("On Hold", 4),
        ("Delayed", 5),
    ]
    for name, ordering in defaults:
        StatusConfig.objects.update_or_create(
            name=name,
            defaults={"ordering": ordering, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_domainindicator"),
    ]

    operations = [
        migrations.RunPython(seed_statuses, migrations.RunPython.noop),
    ]
