# Generated by Django 5.2.3 on 2025-12-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_seed_status_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Mentee Profile',
                'verbose_name_plural': 'Mentee Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.mentee',),
        ),
    ]
