# Generated by Django 6.0.3 on 2026-03-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_diaryentry_profileartifact_reflectivereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text='All roles assigned to this user'),
        ),
    ]
