# Generated by Django 6.0.3 on 2026-03-20 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customuser_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('file_upload', models.FileField(upload_to='repository/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('role_visibility', models.CharField(choices=[('all', 'All Users'), ('admin', 'Admins Only'), ('mentor', 'Mentors Only'), ('volunteer', 'Volunteers Only'), ('leadership', 'Leadership Only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_model', models.CharField(help_text='e.g., MenteeAssessment, ReflectiveReport', max_length=100)),
                ('linked_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.repositoryasset')),
            ],
        ),
    ]
