# Generated by Django 6.0.3 on 2026-03-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_backfill_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='diary_entries/'),
        ),
        migrations.AddField(
            model_name='reflectivereport',
            name='reporter_class_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reflectivereport',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reflectivereport',
            name='reporter_identifier',
            field=models.CharField(blank=True, help_text='Register number or volunteer ID', max_length=100),
        ),
        migrations.AddField(
            model_name='reflectivereport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reflectivereport',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='record_type',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('objective', 'Objective'), ('year_plan', 'Year Plan'), ('reflective_report', 'Reflective Report'), ('work_diary', 'Work Diary'), ('transcript', 'Volunteer Transcript')], max_length=30),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='review_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Returned', 'Returned for Revision')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_group',
            field=models.CharField(choices=[('admin', 'Admin'), ('endorser', 'Endorser'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('reviewer', 'Reviewer'), ('volunteer', 'Volunteer'), ('community_leader', 'Community Leader'), ('faculty_leader', 'Faculty Leader'), ('strategic_team', 'Strategic Team'), ('principal', 'Principal'), ('coordinator', 'Coordinator'), ('all', 'All Users')], max_length=20),
        ),
    ]
