# Generated by Django 6.0.3 on 2026-03-21 10:35

from django.db import migrations, models


ROLE_MAP = {
    "executive": "admin",
    "coordinator": "admin",
}

VALID_ROLES = {
    "admin",
    "endorser",
    "mentor",
    "mentee",
    "volunteer",
    "approval",
}


def _dedupe(items):
    seen = []
    for item in items:
        if item and item not in seen:
            seen.append(item)
    return seen


def merge_admin_roles(apps, schema_editor):
    CustomUser = apps.get_model("core", "CustomUser")
    Notification = apps.get_model("core", "Notification")

    for user in CustomUser.objects.all():
        mapped_role = ROLE_MAP.get(user.role, user.role)
        mapped_roles = [ROLE_MAP.get(role, role) for role in (user.roles or [])]
        mapped_roles = [role for role in mapped_roles if role in VALID_ROLES]

        if user.is_superuser and "admin" not in mapped_roles:
            mapped_roles.insert(0, "admin")
        if mapped_role and mapped_role not in mapped_roles:
            mapped_roles.insert(0, mapped_role)
        if not mapped_role and mapped_roles:
            mapped_role = mapped_roles[0]

        mapped_roles = _dedupe(mapped_roles)
        update_fields = []
        if mapped_role != user.role:
            user.role = mapped_role
            update_fields.append("role")
        if mapped_roles != (user.roles or []):
            user.roles = mapped_roles
            update_fields.append("roles")
        if update_fields:
            user.save(update_fields=update_fields)

    for notification in Notification.objects.all():
        mapped_group = ROLE_MAP.get(notification.target_group, notification.target_group)
        if mapped_group != notification.target_group:
            notification.target_group = mapped_group
            notification.save(update_fields=["target_group"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.RunPython(merge_admin_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("endorser", "Endorser"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                    ("volunteer", "Volunteer"),
                    ("approval", "Approval"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="target_group",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("endorser", "Endorser"),
                    ("mentor", "Mentor"),
                    ("mentee", "Mentee"),
                    ("volunteer", "Volunteer"),
                    ("approval", "Approval"),
                    ("all", "All Users"),
                ],
                max_length=20,
            ),
        ),
    ]
