# Generated by Django 6.0.3 on 2026-03-21 06:47

from django.db import migrations, models


VALID_ROLES = {
    "admin",
    "endorser",
    "mentor",
    "mentee",
    "volunteer",
}


def _dedupe(items):
    seen = []
    for item in items:
        if item and item not in seen:
            seen.append(item)
    return seen


def remove_approval_role(apps, schema_editor):
    CustomUser = apps.get_model("core", "CustomUser")
    Notification = apps.get_model("core", "Notification")
    DiaryEntry = apps.get_model("core", "DiaryEntry")

    for user in CustomUser.objects.all():
        current_roles = list(user.roles or [])
        mapped_roles = [role for role in current_roles if role in VALID_ROLES and role != "approval"]

        replacement_role = user.role
        if user.role == "approval":
            if "endorser" in current_roles:
                replacement_role = "endorser"
            elif "mentor" in current_roles:
                replacement_role = "mentor"
            else:
                replacement_role = "mentor"

        if replacement_role not in VALID_ROLES:
            replacement_role = "admin" if user.is_superuser else (mapped_roles[0] if mapped_roles else "mentor")

        if replacement_role not in mapped_roles:
            mapped_roles.insert(0, replacement_role)
        if user.is_superuser and "admin" not in mapped_roles:
            mapped_roles.insert(0, "admin")

        mapped_roles = _dedupe(mapped_roles)
        update_fields = []
        if user.role != replacement_role:
            user.role = replacement_role
            update_fields.append("role")
        if list(user.roles or []) != mapped_roles:
            user.roles = mapped_roles
            update_fields.append("roles")
        if update_fields:
            user.save(update_fields=update_fields)

    Notification.objects.filter(target_group="approval").update(target_group="admin")
    DiaryEntry.objects.filter(review_status="Reviewed").update(review_status="Approved")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_admin_roles'),
    ]

    operations = [
        migrations.RunPython(remove_approval_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('endorser', 'Endorser'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('volunteer', 'Volunteer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='review_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Returned', 'Returned for Revision')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_group',
            field=models.CharField(choices=[('admin', 'Admin'), ('endorser', 'Endorser'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('volunteer', 'Volunteer'), ('all', 'All Users')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reflectivereport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Approved', 'Approved'), ('Returned', 'Returned for Revision')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteertranscript',
            name='approval_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Review', 'Pending Review'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved')], default='Draft', max_length=20),
        ),
    ]
