# Generated by Django 6.0.3 on 2026-03-21 08:30

from django.db import migrations, models


def approve_pending_admin_transcripts(apps, schema_editor):
    VolunteerTranscript = apps.get_model("core", "VolunteerTranscript")
    VolunteerTranscript.objects.filter(approval_status="Pending Approval").update(approval_status="Approved")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_volunteerreportingassignment'),
    ]

    operations = [
        migrations.RunPython(approve_pending_admin_transcripts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='volunteertranscript',
            name='approval_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved')], default='Draft', max_length=20),
        ),
    ]
