# Generated by Django 6.0.3 on 2026-03-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_volunteertranscript_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryasset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
