# Generated by Django 6.0.3 on 2026-03-21 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_repositoryasset_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='assigned', max_length=20)),
                ('progress_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_assignments', to=settings.AUTH_USER_MODEL)),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.workschedule')),
            ],
            options={
                'ordering': ['work_schedule__due_date', 'assignee__first_name', 'assignee__username'],
                'unique_together': {('work_schedule', 'assignee')},
            },
        ),
    ]
