from django.urls import path
from . import views



urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('mentee-dashboard/', views.mentee_dashboard_view, name='mentee_dashboard'),
    path('objectives/', views.objective_list_view, name='objective_list'),
    path('objectives/new/', views.objective_create_view, name='objective_create'),
    path('objectives/<int:objective_id>/edit/', views.objective_edit_view, name='objective_edit'),
    path('year-plans/', views.year_plan_list_view, name='year_plan_list'),
    path('year-plans/new/', views.year_plan_create_view, name='year_plan_create'),
    path('year-plans/<int:year_plan_id>/edit/', views.year_plan_edit_view, name='year_plan_edit'),
    path('assessments/', views.mentee_assessment_list_view, name='mentee_assessment_list'),
    path('mentor/mentees/', views.mentor_mentee_list_view, name='mentor_mentee_list'),
    path('mentor/mentees/<int:mentee_id>/objectives/', views.mentor_objective_list_view, name='mentor_objective_list'),
    path('mentor/objectives/<int:objective_id>/review/', views.mentor_objective_update_view, name='mentor_objective_update'),
    path('mentor/mentees/<int:mentee_id>/year-plans/', views.mentor_year_plan_list_view, name='mentor_year_plan_list'),
    path('mentor/year-plans/<int:year_plan_id>/review/', views.mentor_year_plan_update_view, name='mentor_year_plan_update'),
    path('mentor/mentees/<int:mentee_id>/assessments/', views.mentor_assessment_list_view, name='mentor_assessment_list'),
    path('mentor/mentees/<int:mentee_id>/assessments/new/', views.mentor_assessment_create_view, name='mentor_assessment_create'),
    path('mentees/<int:mentee_id>/export/', views.export_mentee_progress_csv, name='export_mentee_progress'),
    path('mentees/<int:mentee_id>/export-excel/', views.export_mentee_progress_excel, name='export_mentee_progress_excel'),
    path('dip-yclp/', views.dip_yclp_view, name='dip_yclp'),
    path('dip-mentee/', views.dip_mentee_view, name='dip_mentee'),
    path('profile/', views.profile_view, name='profile'),
    path('work-diary/', views.work_diary_view, name='work_diary'),
    path('work-diary/all/', views.work_diary_list_view, name='work_diary_list'),
    path('reflective-report/', views.reflective_report_view, name='reflective_report'),
    path('reflective-report/all/', views.reflective_report_list_view, name='reflective_report_list'),
    path('repository/', views.repository_view, name='repository'),
    path('repository/<int:asset_id>/toggle-status/', views.toggle_repository_asset_status_view, name='toggle_repository_asset_status'),
    path('notification/', views.notification_center_view, name='notification'),
    path('transcript/', views.transcript_view, name='transcript'),
    path('transcript/generate/', views.generate_transcript_view, name='generate_transcript'),
    path('transcript/<int:transcript_id>/review/', views.review_transcript_view, name='review_transcript'),
    path('settings/', views.settings_view, name='settings'),
    path('workflow-guide/', views.workflow_guide_view, name='workflow_guide'),
    path('new-activity/', views.new_activity, name='new_activity'),
    path('my-activities/', views.my_activities_view, name='my-activities'),
    path("role-redirect/", views.role_redirect_view, name="role-redirect"),
    path("switch-role/", views.switch_role_view, name="switch_role"),
    path("volunteer-dashboard/", views.volunteer_dashboard_view, name="volunteer_dashboard"),
    path("approval-dashboard/", views.approval_dashboard_view, name="approval_dashboard"),
    path("approval-queue/", views.approval_queue_view, name="approval_queue"),
    path("approval/reflective-reports/<int:report_id>/", views.review_reflective_report_view, name="review_reflective_report"),
    path("approval/work-diaries/<int:diary_id>/", views.review_work_diary_view, name="review_work_diary"),
    path("volunteers/<int:user_id>/profile/public/", views.volunteer_public_profile_view, name="volunteer_public_profile"),
    path("volunteers/<int:user_id>/profile/internal/", views.volunteer_internal_profile_view, name="volunteer_internal_profile"),
    path("admin-dashboard/", views.admin_dashboard_view, name="admin_dashboard"),
    path("admin-config/", views.admin_config_home_view, name="admin_config_home"),
    path("admin-config/<str:config_key>/", views.admin_config_list_view, name="admin_config_list"),
    path("admin-config/<str:config_key>/<int:item_id>/edit/", views.admin_config_edit_view, name="admin_config_edit"),
    path("admin-config/<str:config_key>/<int:item_id>/delete/", views.admin_config_delete_view, name="admin_config_delete"),
    path("manage-user/", views.manage_user_view, name="manage_user"),
    path("user-role-manager/", views.user_role_manager_view, name="user_role_manager"),
    path("update-user-roles/<int:user_id>/", views.update_user_roles_view, name="update_user_roles"),
    path("add-user/", views.add_user_view, name="add_user"),
    path("edit-user/<int:user_id>/", views.edit_user_view, name="edit_user"),
    path("delete-user/<int:user_id>/", views.delete_user_view, name="delete_user"),
    path('manage-assignment/', views.manage_assignment, name='manage_assignment'),
    path('manage-mentee-assignments/', views.manage_mentee_assignments_view, name='manage_mentee_assignments'),
    path('manage-volunteer-reporting-assignments/', views.manage_volunteer_reporting_assignments_view, name='manage_volunteer_reporting_assignments'),
    path('manage-work-items/', views.manage_work_items_view, name='manage_work_items'),
    path('user/<int:user_id>/view/', views.view_user, name='view_user'),
    path('users/<int:user_id>/export/', views.export_user_activities_excel, name='export_user_activities'),
    path('users/bulk-upload/', views.bulk_upload_users_view, name='bulk_upload_users'),
    path("admin-dashboard/export/reflective-reports/", views.export_reflective_reports_excel, name="export_reflective_reports"),
    path("admin-dashboard/export/work-diaries/", views.export_work_diaries_excel, name="export_work_diaries"),
    path("profile/edit/", views.profile_edit, name="profile_edit"),
    path('endorser-dashboard/', views.endorser_dashboard, name='endorser_dashboard'),
    path('endorser/work-schedule/', views.endorser_work_schedule, name='endorser_work_schedule'),
    path('work-items/', views.assigned_work_items_view, name='assigned_work_items'),
    path('work-items/<int:assignment_id>/status/', views.update_work_item_status_view, name='update_work_item_status'),
    path('endorser/profile/', views.endorser_profile, name='endorser_profile'),
    path('endorser/profile/edit/', views.endorser_edit_profile, name='endorser_edit_profile'),
    path('download-user-template/', views.download_user_template, name='download_user_template'),
    path('download-mentee-template/', views.download_mentee_template, name='download_mentee_template'),
    path('mentees/bulk-upload/', views.bulk_upload_mentees_view, name='bulk_upload_mentees'),
    path('mentees/upload-log/', views.mentee_upload_log_view, name='mentee_upload_log'),
    path('admin-notifications/', views.admin_notification_view, name='admin_notifications'),
    path('admin-notifications/<int:notification_id>/delete/', views.admin_notification_delete_view, name='admin_notification_delete'),
    path('get-assigned-mentors/', views.get_assigned_mentors, name='get_assigned_mentors'),
    path('assign-mentors/', views.assign_mentors, name='assign_mentors'),
    path('unassign-mentor/', views.unassign_mentor, name='unassign_mentor'),
    path('activity-log/', views.activity_log, name='activity_log'),
    path('mentor/<int:mentor_id>/activity/', views.mentor_activity_list, name='mentor_activity'),
    path('add-remark/', views.add_remark, name='add_remark'),
    path('mentor-profile/', views.mentor_profile, name='mentor_profile'),
    


]
